version: "3"
services:
  frontend:
    build: frontend/
    restart: always
    ports:
      - "80:80"
    links:
      - "backend"
  backend:
    build: backend/
    restart: always
    links:
      - "db"
      - "scheduler"
    depends_on:
      - "db"
      - "scheduler"
    ports:
      - "5000:80"
  scheduler:
    build: scheduler/
    depends_on:
      - "db"
    ports:
      - "5050:80"
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
