version: "3"
services:
  frontend:
    build: frontend/
    restart: always
    ports:
      - "80:80"
  backend:
    build: backend/
    restart: always
    links:
      - "db"
    depends_on:
      - "db"
      - "scheduler"
    ports:
      - "5000:5000"
  scheduler:
    build: scheduler/
    depends_on:
      - "db"
    ports:
      - "5050:5050"
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - "db"
    depends_on:
      - "db"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
