version: "3"
services:
  frontend:
    image: ghcr.io/aitorru/fullstack-page-aitorru-frontend:latest
    restart: always
    ports:
      - "80:80"
    links:
      - "backend"
  backend:
    image: ghcr.io/aitorru/fullstack-page-aitorru-backend:latest
    restart: always
    links:
      - "db"
      - "scheduler"
    depends_on:
      - "db"
      - "scheduler"
    ports:
      - "5000:80"
  scheduler:
    image: ghcr.io/aitorru/fullstack-page-aitorru-scheduler:latest
    depends_on:
      - "db"
    ports:
      - "5050:80"
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
